plugins {
    id 'java-library'
    id 'maven-publish'
}

version = lib_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'com.google.code.gson:gson:2.10.1'
    compileOnly 'org.jetbrains:annotations:24.1.0'
    compileOnly 'com.google.errorprone:error_prone_annotations:2.18.0'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}

sourceSets.main.resources {
    srcDir '.'
    include 'LICENSE'
    include 'NOTICE'
}

tasks.named('jar', Jar) {
    enabled = false
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}